workflows:
  ios-testflight:
    name: iOS TestFlight Derlemesi
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: posof
    environment:
      flutter: stable
    scripts:
      - name: Flutter Paketlerini Yukle
        script: flutter pub get
      - name: Mac Guvenlik Anahtarligini Baslat
        script: keychain initialize
      - name: Sertifika Anahtari Olustur
        script: |
          openssl genrsa -out /tmp/certificate_key.pem 2048
          echo "CERTIFICATE_PRIVATE_KEY<<EOF" >> $CM_ENV
          cat /tmp/certificate_key.pem >> $CM_ENV
          echo "EOF" >> $CM_ENV
      - name: Apple Sertifikalarini Otomatik Olustur
        script: app-store-connect fetch-signing-files "com.drksistem.altinasistanim" --type IOS_APP_STORE --create
      - name: Sertifikalari Sisteme Ekle
        script: keychain add-certificates
      - name: Xcode Projesini Imzalamaya Hazirla
        script: xcode-project use-profiles
      - name: iOS Uygulamasini Derle (IPA)
        script: flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
